"""Codegen: emit src/fheroes2/heroes/heroes_specialty.{h,cpp} from hero_manifest.json.

The C++ engine reads from a static `kHeroSpecialties[]` table indexed by hero id.
Index 0 (UNKNOWN) and any hero without a specialty become a default-constructed
`HeroSpecialty` (kind == NONE).
"""

from __future__ import annotations

from pathlib import Path

from ..models.hero_config import HeroConfig


_HEADER_FILE = "heroes_specialty.h"
_SOURCE_FILE = "heroes_specialty.cpp"
_RGBA_INCLUDE_FILE = "heroes_specialty_rgba.inl"
_RGBA_SMALL_INCLUDE_FILE = "heroes_specialty_rgba_small.inl"

_GENERATED_BANNER = (
    "// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py\n"
    "// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.\n"
    "// Edit the specialty in the Python sprite editor and re-export instead.\n"
)


def _h_contents() -> str:
    return _GENERATED_BANNER + """
#pragma once

#include <vector>

// HoMM3-style hero specialty: a tagged choice of spell / unit / resource boost.
// Static per-hero data — populated at codegen time from hero_manifest.json.
struct HeroSpecialty
{
    enum Kind : int
    {
        NONE = 0,
        SPELL,
        UNIT,
        RESOURCE,
    };

    Kind kind = NONE;

    // Spell payload (kind == SPELL).
    // The selected spell is also implicitly added to the hero's spell book
    // (engine consumers should treat `spellId` as both "boost target" and
    // "guaranteed-known spell").
    int spellId = 0;
    int damageBonusPercent = 0;
    int spCostReduction = 0;

    // Unit payload (kind == UNIT). The bonus applies to any troop whose
    // monster ID is listed here, so a designer can pick a tier chain
    // (Pikeman + Veteran Pikeman) or a thematic group (all dragons) and the
    // bonus survives in-game upgrades without extra engine logic.
    std::vector<int> monsterIds;
    int atkBonus = 0;
    int defBonus = 0;
    int speedBonus = 0;

    // Resource payload (kind == RESOURCE) — resourceId is a bit flag from Resource::
    int resourceId = 0;
    int amountPerDay = 0;
};

const HeroSpecialty & getHeroSpecialty( const int heroId );
"""


def _format_entry(cfg: HeroConfig | None) -> str:
    """Return one C++ aggregate-initialiser for a single hero's specialty.

    Field order matches the struct declaration in heroes_specialty.h:
        kind, spellId, damageBonusPercent, spCostReduction,
        monsterIds, atkBonus, defBonus, speedBonus,
        resourceId, amountPerDay.
    """
    if cfg is None:
        return "{}"

    s = cfg.specialty
    if s.kind == "spell":
        return (
            "{ HeroSpecialty::SPELL, "
            f"Spell::{s.spell or 'NONE'}, {s.damage_bonus_percent}, {s.sp_cost_reduction}, "
            "{}, 0, 0, 0, 0, 0 }"
        )
    if s.kind == "unit":
        units = s.units or []
        if units:
            unit_list = ", ".join(f"Monster::{u}" for u in units)
            unit_init = "{ " + unit_list + " }"
        else:
            unit_init = "{}"
        return (
            "{ HeroSpecialty::UNIT, 0, 0, 0, "
            f"{unit_init}, {s.atk_bonus}, {s.def_bonus}, {s.speed_bonus}, "
            "0, 0 }"
        )
    if s.kind == "resource":
        return (
            "{ HeroSpecialty::RESOURCE, 0, 0, 0, {}, 0, 0, 0, "
            f"Resource::{s.resource or 'WOOD'}, {s.amount_per_day} }}"
        )
    return "{}"


def _cpp_contents(heroes: dict[str, HeroConfig]) -> str:
    by_id: dict[int, HeroConfig] = {cfg.hero_id: cfg for cfg in heroes.values()}
    max_id = max(by_id.keys(), default=0)

    rows: list[str] = []
    rows.append("    /* UNKNOWN (0) */ {},")
    for hid in range(1, max_id + 1):
        cfg = by_id.get(hid)
        if cfg is None:
            rows.append(f"    /* hero_id {hid} (no manifest entry) */ {{}},")
            continue
        comment = f"/* {cfg.enum} ({hid}) */"
        rows.append(f"    {comment} {_format_entry(cfg)},")

    table_body = "\n".join(rows)

    return _GENERATED_BANNER + f"""
#include "heroes_specialty.h"

#include "monster.h"
#include "resource.h"
#include "spell.h"

#include <cstddef>

namespace
{{
    const HeroSpecialty kHeroSpecialties[] = {{
{table_body}
    }};

    const HeroSpecialty kEmpty{{}};
}}

const HeroSpecialty & getHeroSpecialty( const int heroId )
{{
    if ( heroId < 0 || static_cast<size_t>( heroId ) >= sizeof( kHeroSpecialties ) / sizeof( kHeroSpecialties[0] ) ) {{
        return kEmpty;
    }}
    return kHeroSpecialties[heroId];
}}
"""


def _rgba_inl_contents(heroes: dict[str, HeroConfig]) -> str:
    """Emit the body of the RGBA hero (big portrait) registry."""
    rows: list[str] = []
    for cfg in sorted(heroes.values(), key=lambda c: c.hero_id):
        if not cfg.has_custom_sprites:
            continue
        rows.append(f'                {{ Heroes::{cfg.enum}, "{cfg.prefix}" }},')

    body = "\n".join(rows) if rows else "                // (no heroes have hi-res portraits yet)"

    return (
        "// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py\n"
        "// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.\n"
        "// Hero RGBA registry: each entry maps a hero ID to the PNG prefix at\n"
        "// files/data/sprites/{prefix}_000.png. Populated from heroes whose\n"
        "// hero_manifest.json entry has \"has_custom_sprites\": true.\n"
        f"{body}\n"
    )


def _rgba_small_inl_contents(heroes: dict[str, HeroConfig]) -> str:
    """Emit the body of the RGBA hero SMALL portrait registry."""
    rows: list[str] = []
    for cfg in sorted(heroes.values(), key=lambda c: c.hero_id):
        if not cfg.has_custom_sprites_small:
            continue
        rows.append(f'                {{ Heroes::{cfg.enum}, "{cfg.prefix}" }},')

    body = "\n".join(rows) if rows else "                // (no heroes have hi-res small portraits yet)"

    return (
        "// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py\n"
        "// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.\n"
        "// Hero RGBA SMALL registry: maps a hero ID to the PNG prefix at\n"
        "// files/data/sprites/{prefix}_small_000.png. Populated from heroes whose\n"
        "// hero_manifest.json entry has \"has_custom_sprites_small\": true.\n"
        f"{body}\n"
    )


def export_specialties(heroes: dict[str, HeroConfig], dst_dir: Path) -> tuple[Path, Path, Path, Path]:
    """Write heroes_specialty.h + .cpp + both .inl files into `dst_dir`.
    Returns the four paths."""
    dst_dir.mkdir(parents=True, exist_ok=True)
    h_path = dst_dir / _HEADER_FILE
    cpp_path = dst_dir / _SOURCE_FILE
    inl_path = dst_dir / _RGBA_INCLUDE_FILE
    inl_small_path = dst_dir / _RGBA_SMALL_INCLUDE_FILE
    h_path.write_text(_h_contents(), encoding="utf-8", newline="\n")
    cpp_path.write_text(_cpp_contents(heroes), encoding="utf-8", newline="\n")
    inl_path.write_text(_rgba_inl_contents(heroes), encoding="utf-8", newline="\n")
    inl_small_path.write_text(_rgba_small_inl_contents(heroes), encoding="utf-8", newline="\n")
    return h_path, cpp_path, inl_path, inl_small_path


def project_root() -> Path:
    """Resolve the project root from this file's location."""
    return Path(__file__).parent.parent.parent.parent


def default_dst_dir() -> Path:
    return project_root() / "src" / "fheroes2" / "heroes"
