// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py
// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.
// Hero RGBA registry: each entry maps a hero ID to the PNG prefix at
// files/data/sprites/{prefix}_000.png. Populated from heroes whose
// hero_manifest.json entry has "has_custom_sprites": true.
                { Heroes::LORDKILBURN, "hero_lord_kilburn" },
                { Heroes::GVENNETH, "hero_gvenneth" },
                { Heroes::TYRO, "hero_tyro" },
                { Heroes::RUBY, "hero_ruby" },
                { Heroes::ERGON, "hero_ergon" },
                { Heroes::ASTRA, "hero_astra" },
                { Heroes::NATASHA, "hero_natasha" },
                { Heroes::REBECCA, "hero_rebecca" },
                { Heroes::CARLAWN, "hero_carlawn" },
                { Heroes::KASTORE, "hero_kastore" },
                { Heroes::FALAGAR, "hero_falagar" },
                { Heroes::WRATHMONT, "hero_wrathmont" },
                { Heroes::MYRA, "hero_myra" },
                { Heroes::FLINT, "hero_flint" },
                { Heroes::DAWN, "hero_dawn" },
                { Heroes::HALON, "hero_halon" },
                { Heroes::MYRINI, "hero_myrini" },
                { Heroes::KALINDRA, "hero_kalindra" },
                { Heroes::MANDIGAL, "hero_mandigal" },
                { Heroes::DARLANA, "hero_darlana" },
                { Heroes::ROXANA, "hero_roxana" },
                { Heroes::SANDRO, "hero_sandro" },
                { Heroes::CELIA, "hero_celia" },
