// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py
// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.
// Hero RGBA SMALL registry: maps a hero ID to the PNG prefix at
// files/data/sprites/{prefix}_small_000.png. Populated from heroes whose
// hero_manifest.json entry has "has_custom_sprites_small": true.
                { Heroes::NATASHA, "hero_natasha" },
                { Heroes::CARLAWN, "hero_carlawn" },
