// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py
// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.
// Hero RGBA registry: each entry maps a hero ID to the PNG prefix at
// files/data/sprites/{prefix}_000.png. Populated from heroes whose
// hero_manifest.json entry has "has_custom_sprites": true.
                { Heroes::GVENNETH, "hero_gvenneth" },
                { Heroes::ERGON, "hero_ergon" },
                { Heroes::NATASHA, "hero_natasha" },
                { Heroes::CARLAWN, "hero_carlawn" },
                { Heroes::DAWN, "hero_dawn" },
                { Heroes::CELIA, "hero_celia" },
