// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py
// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.
// Edit the specialty in the Python sprite editor and re-export instead.

#pragma once

#include <vector>

// HoMM3-style hero specialty: a tagged choice of spell / unit / resource boost.
// Static per-hero data — populated at codegen time from hero_manifest.json.
struct HeroSpecialty
{
    enum Kind : int
    {
        NONE = 0,
        SPELL,
        UNIT,
        RESOURCE,
    };

    Kind kind = NONE;

    // Spell payload (kind == SPELL).
    // The selected spell is also implicitly added to the hero's spell book
    // (engine consumers should treat `spellId` as both "boost target" and
    // "guaranteed-known spell").
    int spellId = 0;
    int damageBonusPercent = 0;
    int spCostReduction = 0;

    // Unit payload (kind == UNIT). The bonus applies to any troop whose
    // monster ID is listed here, so a designer can pick a tier chain
    // (Pikeman + Veteran Pikeman) or a thematic group (all dragons) and the
    // bonus survives in-game upgrades without extra engine logic.
    std::vector<int> monsterIds;
    int atkBonus = 0;
    int defBonus = 0;
    int speedBonus = 0;

    // Resource payload (kind == RESOURCE) — resourceId is a bit flag from Resource::
    int resourceId = 0;
    int amountPerDay = 0;
};

const HeroSpecialty & getHeroSpecialty( const int heroId );
