// AUTO-GENERATED BY tools/sprite_editor/codegen/specialty_export.py
// DO NOT EDIT BY HAND — your changes will be overwritten by the next export.
// Edit the specialty in the Python sprite editor and re-export instead.

#include "heroes_specialty.h"

#include "monster.h"
#include "resource.h"
#include "spell.h"

#include <cstddef>

namespace
{
    const HeroSpecialty kHeroSpecialties[] = {
    /* UNKNOWN (0) */ {},
    /* LORDKILBURN (1) */ { HeroSpecialty::UNIT, 0, 0, 0, { Monster::PEASANT, Monster::MAID }, 4, 4, 1, 0, 0 },
    /* SIRGALLANTH (2) */ {},
    /* ECTOR (3) */ { HeroSpecialty::RESOURCE, 0, 0, 0, {}, 0, 0, 0, Resource::WOOD, 2 },
    /* GVENNETH (4) */ { HeroSpecialty::UNIT, 0, 0, 0, { Monster::CAVALRY, Monster::CHAMPION, Monster::PALADIN, Monster::CRUSADER, Monster::AVENGER }, 5, 5, 1, 0, 0 },
    /* TYRO (5) */ { HeroSpecialty::SPELL, Spell::RESURRECTTRUE, 50, 10, {}, 0, 0, 0, 0, 0 },
    /* AMBROSE (6) */ {},
    /* RUBY (7) */ { HeroSpecialty::RESOURCE, 0, 0, 0, {}, 0, 0, 0, Resource::CRYSTAL, 1 },
    /* MAXIMUS (8) */ {},
    /* DIMITRY (9) */ {},
    /* THUNDAX (10) */ { HeroSpecialty::UNIT, 0, 0, 0, { Monster::OGRE, Monster::OGRE_LORD, Monster::TROLL, Monster::WAR_TROLL }, 3, 4, 1, 0, 0 },
    /* FINEOUS (11) */ {},
    /* JOJOSH (12) */ {},
    /* CRAGHACK (13) */ {},
    /* JEZEBEL (14) */ {},
    /* JACLYN (15) */ {},
    /* ERGON (16) */ { HeroSpecialty::UNIT, 0, 0, 0, { Monster::WOLF, Monster::DACHSHUND }, 5, 2, 1, 0, 0 },
    /* TSABU (17) */ {},
    /* ATLAS (18) */ {},
    /* ASTRA (19) */ {},
    /* NATASHA (20) */ {},
    /* TROYAN (21) */ {},
    /* VATAWNA (22) */ {},
    /* REBECCA (23) */ {},
    /* GEM (24) */ {},
    /* ARIEL (25) */ {},
    /* CARLAWN (26) */ { HeroSpecialty::SPELL, Spell::LIGHTNINGBOLT, 33, 1, {}, 0, 0, 0, 0, 0 },
    /* LUNA (27) */ {},
    /* ARIE (28) */ {},
    /* ALAMAR (29) */ {},
    /* VESPER (30) */ {},
    /* CRODO (31) */ {},
    /* BAROK (32) */ { HeroSpecialty::SPELL, Spell::ARROW, 50, 0, {}, 0, 0, 0, 0, 0 },
    /* KASTORE (33) */ { HeroSpecialty::UNIT, 0, 0, 0, { Monster::GREEN_DRAGON, Monster::RED_DRAGON, Monster::BLACK_DRAGON, Monster::AZURE_DRAGON, Monster::BONE_DRAGON, Monster::BLOOD_DRAGON }, 5, 5, 1, 0, 0 },
    /* AGAR (34) */ {},
    /* FALAGAR (35) */ {},
    /* WRATHMONT (36) */ {},
    /* MYRA (37) */ {},
    /* FLINT (38) */ {},
    /* DAWN (39) */ {},
    /* HALON (40) */ {},
    /* MYRINI (41) */ {},
    /* WILFREY (42) */ {},
    /* SARAKIN (43) */ {},
    /* KALINDRA (44) */ {},
    /* MANDIGAL (45) */ {},
    /* ZOM (46) */ {},
    /* DARLANA (47) */ {},
    /* ZAM (48) */ {},
    /* RANLOO (49) */ {},
    /* CHARITY (50) */ {},
    /* RIALDO (51) */ {},
    /* ROXANA (52) */ {},
    /* SANDRO (53) */ {},
    /* CELIA (54) */ {},
    /* ROLAND (55) */ {},
    /* CORLAGON (56) */ {},
    /* ELIZA (57) */ {},
    /* ARCHIBALD (58) */ {},
    /* HALTON (59) */ {},
    /* BRAX (60) */ {},
    /* SOLMYR (61) */ {},
    /* DAINWIN (62) */ {},
    /* MOG (63) */ {},
    /* UNCLEIVAN (64) */ {},
    /* JOSEPH (65) */ {},
    /* GALLAVANT (66) */ {},
    /* ELDERIAN (67) */ {},
    /* CEALLACH (68) */ {},
    /* DRAKONIA (69) */ {},
    /* MARTINE (70) */ {},
    /* JARKONAS (71) */ {},
    /* DEBUG_HERO (72) */ {},
    };

    const HeroSpecialty kEmpty{};
}

const HeroSpecialty & getHeroSpecialty( const int heroId )
{
    if ( heroId < 0 || static_cast<size_t>( heroId ) >= sizeof( kHeroSpecialties ) / sizeof( kHeroSpecialties[0] ) ) {
        return kEmpty;
    }
    return kHeroSpecialties[heroId];
}
